baseURL = 'https://suhyeojee.github.io/'
languageCode = 'ko-kr'
title = 'ROTOMU'
theme = "PaperMod"

[params]
    ShowCodeCopyButtons = true
    showToc = true           # 모든 포스트에 목차 표시
    TocOpen = false          # 페이지 로드 시 목차를 펼쳐둘지 여부

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"  # 시리즈 기능 추가

[outputs]
    home = ["HTML", "RSS", "JSON"] # 검색용 JSON 파일 생성을 위해 필수

[[menu.main]]
    identifier = "explore"
    name = "Explore"
    url = "/explore/"
    weight = 5

# [[menu.main]]
#     identifier = "search"
#     name = "Search"
#     url = "/search/"
#     weight = 10

# [[menu.main]]
#     identifier = "categories"
#     name = "Categories"
#     url = "/categories/"
#     weight = 20

# [[menu.main]]
#     identifier = "tags"
#     name = "Tags"
#     url = "/tags/"
#     weight = 30

[[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives/"
    weight = 40
